// Pull in required dependencies
// var path = require('path');
var multer = require('multer'),
	bodyParser = require('body-parser'),
	path = require('path');
var fs = require('fs');
var moment = require("moment");
var numeral = require("numeral");



// Import the list of friend entries

// Export API routes
module.exports = function (app) {
	//all friends -- read in --- asynch
	//no problems because it will send to browser
	//line by line as it comes in
	// app.get('/picture/create', function (req, response) {
	// 	console.log("hit the create inside of api routes")
	// });

	app.post('/picture/create', multer({ dest: './app/public/uploads/' }).single('upl'), function (req, res) {
		console.log('did a post inside of api routes');
		console.log(req.file);
		if (!req.file) {
			console.log("No file received");
			return res.send({
				success: false
			});

		} else {
			console.log('file received');
			return res.send({
				success: true
			})
		}
	});


	//this is the routine for pulling images	
	app.post('/picture/create-img2', multer({ dest: './app/public/uploads/' }).single('upl'), function (req, res) {
		console.log('did a post inside of api routes');
		console.log(req.file);
		if (!req.file) {
			console.log("No file received");
			return res.send({
				success: false
			});

		} else {
			console.log('file received');
			return res.send({
				success: true
			})
		}
	});

	var upload = multer({ dest: __dirname + '/public/uploads/' });
	var type = upload.single('upl');

	var uploadFile = __dirname;
	var newLen = uploadFile.length - 7;
	var timeStamp = moment().unix();
	uploadFile = uploadFile.substr(0, newLen) + '/public/uploads/' + "Audit" + timeStamp + ".png";
	//var uploadFile = '../public/uploads/' + "test1.png";
	console.log(uploadFile);

	app.post('/picture/create-img', type, function (req, res) {
		console.log("\n\n from upload");

		//console.log( Object.keys(req.body)[0]);
		var img = "" + Object.keys(req.body)[0];
		//console.log(img);
		img2 = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAAAAACPAi4CAAAAB3RJTUUH1QEHDxEhOnxCRgAAAAlwSFlzAAAK8AAACvABQqw0mAAAAXBJREFUeNrtV0FywzAIxJ3+K/pZyctKXqamji0htEik9qEHc3JkWC2LRPCS6Zh9HIy/AP4FwKf75iHEr6eU6Mt1WzIOFjFL7IFkYBx3zWBVkkeXAUCXwl1tvz2qdBLfJrzK7ixNUmVdTIAB8PMtxHgAsFNNkoExRKA+HocriOQAiC+1kShhACwSRGAEwPP96zYIoE8Pmph9qEWWKcCWRAfA/mkfJ0F6dSoA8KW3CRhn3ZHcW2is9VOsAgoqHblncAsyaCgcbqpUZQnWoGTcp/AnuwCoOUjhIvCvN59UBeoPZ/AYyLm3cWVAjxhpqREVaP0974iVwH51d4AVNaSC8TRNNYDQEFdlzDW9ob10YlvGQm0mQ+elSpcCCBtDgQD7cDFojdx7NIeHJkqi96cOGNkfZOroZsHtlPYoR7TOp3Vmfa5+49uoSSRyjfvc0A1kLx4KC6sNSeDieD1AWhrJLe0y+uy7b9GjP83l+m68AJ72AwSRPN5g7uwUAAAAAElFTkSuQmCC";
		img = img.split(' ').join('+');
		console.log("\n\n");
		if ( img==img2 ) {
			console.log("both are equal");
		} else {
			console.log("not equal");
			console.log("len 1=" + img.length);
			console.log("len 2=" + img2.length);
		};
/*
		var tempStr_1 = tempStr.substr(0, 40);
		var base64Data = tempStr.replace(/^data:image\/png;base64,/, "");
		var dataIn = tempStr.replace(/^data:image\/png;base64,/, "");
		var tempStr_2 = base64Data.substr(0, 40);
		console.log(tempStr_1 + "-and-" + tempStr_2);

		//var data = img.replace(/^data:image\/\w+;base64,/, "");
		var buf = new Buffer(dataIn, 'base64');
*/
		var ext = img.split(';')[0].match(/jpeg|png|gif/)[0];
		// strip off the data: url prefix to get just the base64-encoded bytes
		var data = img.replace(/^data:image\/\w+;base64,/, "");
		var buf = new Buffer(data, 'base64');

		var uploadFile = __dirname;
		var newLen = uploadFile.length - 7;
		var timeStamp = moment().unix();
		uploadFile = uploadFile.substr(0, newLen) + '/public/uploads/' + "Audit" + timeStamp + ".png";
		
		fs.writeFile(uploadFile, buf, function(err) {
			if( err ) console.log ("error writing image = " + err);
		});

	});

	app.post('/picture/create-img3', type, function (req, res) {

		var fs = require('fs');
		// string generated by canvas.toDataURL()
		var img = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAAAAACPAi4CAAAAB3RJTUUH1QEHDxEhOnxCRgAAAAlwSFlzAAAK8AAACvABQqw0mAAAAXBJREFUeNrtV0FywzAIxJ3+K/pZyctKXqamji0htEik9qEHc3JkWC2LRPCS6Zh9HIy/AP4FwKf75iHEr6eU6Mt1WzIOFjFL7IFkYBx3zWBVkkeXAUCXwl1tvz2qdBLfJrzK7ixNUmVdTIAB8PMtxHgAsFNNkoExRKA+HocriOQAiC+1kShhACwSRGAEwPP96zYIoE8Pmph9qEWWKcCWRAfA/mkfJ0F6dSoA8KW3CRhn3ZHcW2is9VOsAgoqHblncAsyaCgcbqpUZQnWoGTcp/AnuwCoOUjhIvCvN59UBeoPZ/AYyLm3cWVAjxhpqREVaP0974iVwH51d4AVNaSC8TRNNYDQEFdlzDW9ob10YlvGQm0mQ+elSpcCCBtDgQD7cDFojdx7NIeHJkqi96cOGNkfZOroZsHtlPYoR7TOp3Vmfa5+49uoSSRyjfvc0A1kLx4KC6sNSeDieD1AWhrJLe0y+uy7b9GjP83l+m68AJ72AwSRPN5g7uwUAAAAAElFTkSuQmCC";
		// var img = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0"
		// 	+ "NAAAAKElEQVQ4jWNgYGD4Twzu6FhFFGYYNXDUwGFpIAk2E4dHDRw1cDgaCAASFOffhEIO"
		// 	+ "3gAAAABJRU5ErkJggg==";
		// Grab the extension to resolve any image error
		var ext = img.split(';')[0].match(/jpeg|png|gif/)[0];
		// strip off the data: url prefix to get just the base64-encoded bytes
		var data = img.replace(/^data:image\/\w+;base64,/, "");
		var buf = new Buffer(data, 'base64');

		var uploadFile = __dirname;
		var newLen = uploadFile.length - 7;
		uploadFile = uploadFile.substr(0, newLen) + '/public/uploads/' + "test2.png";
		fs.writeFile(uploadFile, buf, function(err) {
			console.log("error writing the image to file: " + err);
		});
		//			fs.writeFile('image.' + ext, buf);
	});


};

// //for storage of pictures
// import bodyParser from 'body-parser';
// import morgan from 'morgan';
// import express from 'express';
// const app2 = express();
// app2.use(bodyParser.json());
// app2.use(bodyParser.urlencoded({extended: true}));
// app2.use(morgan('dev'));


// //this is the picture_controller.js file
// //really /picture
// router.get('/', function(req,res) {
//   res.render('../app/views/camera');
// });

// router.post('/create', upload.single('avatar'),  function(req, res) {
//   console.log("hit the picture create route");
//   const storage = multer.diskStorage({
//     destination: '/public/uploads',
//     filename: function (req, file, callback) {
//       //..
//     }
//   });


// });
